import jsPDF from 'jspdf';
import type { NarrativeSchema, BusinessContext } from '@/lib/types';

interface ExportOptions {
  watermark?: boolean;
}

export const exportToPDF = (
  narrative: NarrativeSchema,
  businessContext: BusinessContext | null,
  title?: string,
  options: ExportOptions = {}
): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = margin;

  // Title
  const docTitle = title || businessContext?.companyName || 'Narrative';
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(docTitle, margin, yPosition);
  yPosition += 15;

  // Subtitle with company context
  if (businessContext) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`${businessContext.industry} | ${businessContext.brandVoice}`, margin, yPosition);
    yPosition += 10;
  }

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Sections
  narrative.sections.forEach((section, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = margin;
    }

    // Section number
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Section ${index + 1}`, margin, yPosition);
    yPosition += 6;

    // Section title
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(section.title, margin, yPosition);
    yPosition += 10;

    // Section content
    if (section.content) {
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(section.content, contentWidth);
      doc.text(lines, margin, yPosition);
      yPosition += lines.length * 6 + 5;
    }

    // Section items
    if (section.items && section.items.length > 0) {
      doc.setFontSize(10);
      section.items.forEach((item) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = margin;
        }
        const bulletLines = doc.splitTextToSize(`• ${item}`, contentWidth - 5);
        doc.text(bulletLines, margin + 5, yPosition);
        yPosition += bulletLines.length * 5 + 2;
      });
    }

    yPosition += 10;
  });

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Watermark for free tier
    if (options.watermark) {
      doc.setFontSize(48);
      doc.setTextColor(200, 200, 200);
      doc.text(
        'Made with Conclusiv',
        pageWidth / 2,
        pageHeight / 2,
        { 
          align: 'center',
          angle: 45,
        }
      );
    }
    
    // Page footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    
    const footerText = options.watermark 
      ? `Page ${i} of ${pageCount} | Made with Conclusiv - conclusiv.app`
      : `Page ${i} of ${pageCount} | Generated by Conclusiv`;
    
    doc.text(
      footerText,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  const fileName = `${docTitle.replace(/\s+/g, '-').toLowerCase()}-narrative.pdf`;
  doc.save(fileName);
};
