import PptxGenJS from 'pptxgenjs';
import type { NarrativeSchema, BusinessContext } from '@/lib/types';

export const exportToPPTX = (
  narrative: NarrativeSchema,
  businessContext: BusinessContext | null,
  title?: string
): void => {
  const pptx = new PptxGenJS();
  
  const docTitle = title || businessContext?.companyName || 'Narrative';
  pptx.title = docTitle;
  pptx.author = 'Conclusiv';
  pptx.subject = 'Narrative Presentation';

  // Define colors based on narrative color theme
  const colors = {
    darkCinematic: { bg: '0D0D0D', text: 'FFFFFF', accent: '8B5CF6' },
    cleanWhite: { bg: 'FFFFFF', text: '1A1A1A', accent: '3B82F6' },
    warmNeutral: { bg: 'F5F5F4', text: '292524', accent: 'D97706' },
    deepOcean: { bg: '0F172A', text: 'F1F5F9', accent: '06B6D4' },
  };

  const theme = colors[narrative.colorTheme] || colors.darkCinematic;

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: theme.bg };
  
  titleSlide.addText(docTitle, {
    x: 0.5,
    y: 2,
    w: '90%',
    h: 1.5,
    fontSize: 44,
    bold: true,
    color: theme.text,
    align: 'center',
  });

  if (businessContext) {
    titleSlide.addText(`${businessContext.industry}`, {
      x: 0.5,
      y: 3.5,
      w: '90%',
      h: 0.5,
      fontSize: 18,
      color: theme.accent,
      align: 'center',
    });

    titleSlide.addText(businessContext.brandVoice, {
      x: 0.5,
      y: 4.2,
      w: '90%',
      h: 0.5,
      fontSize: 14,
      color: theme.text,
      align: 'center',
      italic: true,
    });
  }

  // Content slides for each section
  narrative.sections.forEach((section, index) => {
    const slide = pptx.addSlide();
    slide.background = { color: theme.bg };

    // Section number
    slide.addText(`${index + 1}`, {
      x: 0.5,
      y: 0.3,
      w: 0.5,
      h: 0.5,
      fontSize: 12,
      color: theme.accent,
    });

    // Section title
    slide.addText(section.title, {
      x: 0.5,
      y: 0.8,
      w: '90%',
      h: 1,
      fontSize: 32,
      bold: true,
      color: theme.text,
    });

    // Section content
    if (section.content) {
      slide.addText(section.content, {
        x: 0.5,
        y: 2,
        w: '90%',
        h: 2,
        fontSize: 18,
        color: theme.text,
        valign: 'top',
      });
    }

    // Section items as bullet points
    if (section.items && section.items.length > 0) {
      const bulletText = section.items.map((item) => ({
        text: item,
        options: { bullet: { code: '2022' }, fontSize: 14, color: theme.text },
      }));

      slide.addText(bulletText, {
        x: 0.5,
        y: section.content ? 4 : 2,
        w: '90%',
        h: 2.5,
        valign: 'top',
      });
    }
  });

  // Thank you slide
  const endSlide = pptx.addSlide();
  endSlide.background = { color: theme.bg };
  
  endSlide.addText('Thank You', {
    x: 0.5,
    y: 2.5,
    w: '90%',
    h: 1,
    fontSize: 44,
    bold: true,
    color: theme.text,
    align: 'center',
  });

  endSlide.addText('Generated by Conclusiv', {
    x: 0.5,
    y: 4,
    w: '90%',
    h: 0.5,
    fontSize: 12,
    color: theme.accent,
    align: 'center',
  });

  // Save the presentation
  const fileName = `${docTitle.replace(/\s+/g, '-').toLowerCase()}-presentation`;
  pptx.writeFile({ fileName });
};
