import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link to="/">
          <Button variant="ghost" className="mb-8">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Conclusiv
          </Button>
        </Link>

        <h1 className="text-3xl font-bold mb-2">Terms and Conditions</h1>
        <p className="text-muted-foreground mb-8">Last updated: December 5, 2025</p>

        <div className="prose prose-invert max-w-none space-y-6 text-foreground/80">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using Conclusiv ("the Service"), operated by Mindmaker LLC ("we," "us," or "our"), 
              you agree to be bound by these Terms and Conditions. If you do not agree to these terms, 
              please do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>
              Conclusiv is an AI-powered business narrative generator that transforms research and content 
              into compelling presentations and business plans. The Service uses artificial intelligence 
              to analyze text and generate narrative content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. User Accounts</h2>
            <p>
              To access certain features of the Service, you must create an account. You are responsible for:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. Subscription and Payment</h2>
            <p>
              Some features require a paid subscription. By subscribing, you agree to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Pay all fees associated with your subscription plan</li>
              <li>Automatic renewal unless cancelled before the renewal date</li>
              <li>Provide accurate billing information</li>
            </ul>
            <p className="mt-2">
              Refunds are handled on a case-by-case basis. Contact us at support@mindmaker.llc for refund requests.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use the Service for any illegal purpose</li>
              <li>Upload malicious content or attempt to compromise the Service</li>
              <li>Infringe on intellectual property rights of others</li>
              <li>Use the Service to generate misleading, false, or harmful content</li>
              <li>Resell or redistribute the Service without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Intellectual Property</h2>
            <p>
              <strong>Your Content:</strong> You retain ownership of content you upload to the Service. 
              By uploading content, you grant us a license to process and analyze it for the purpose of 
              providing the Service.
            </p>
            <p className="mt-2">
              <strong>Generated Content:</strong> You own the narratives and presentations generated by the 
              Service from your content. However, the underlying AI models, algorithms, and Service infrastructure 
              remain the property of Mindmaker LLC.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. AI-Generated Content Disclaimer</h2>
            <p>
              Content generated by our AI is provided "as is." While we strive for accuracy, AI-generated 
              content may contain errors, omissions, or inaccuracies. You are responsible for reviewing 
              and verifying all generated content before use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Mindmaker LLC shall not be liable for any indirect, 
              incidental, special, consequential, or punitive damages resulting from your use of the Service, 
              including but not limited to loss of profits, data, or business opportunities.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time for 
              violation of these terms or for any other reason at our discretion. Upon termination, 
              your right to use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">10. Changes to Terms</h2>
            <p>
              We may modify these terms at any time. We will notify users of material changes via email 
              or through the Service. Continued use of the Service after changes constitutes acceptance 
              of the modified terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, 
              United States, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">12. Contact Us</h2>
            <p>
              For questions about these Terms, please contact us at:
            </p>
            <p className="mt-2">
              <strong>Mindmaker LLC</strong><br />
              Email: legal@mindmaker.llc
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
